//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneyPot_Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoneyPot_Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _20140703073725797_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140703073725797_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _20140703073738371_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140703073738371_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _20140703074134235_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140703074134235_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _20140703074206533_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140703074206533_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _201407030742396_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("201407030742396_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon _20140706065133215_easyicon_net_128 {
            get {
                object obj = ResourceManager.GetObject("_20140706065133215_easyicon_net_128", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ALARM3 {
            get {
                return ResourceManager.GetStream("ALARM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 14-4-27 13:19:15.480 Google Chrome Helper[408]: CarbonCore:
        ///[Stop]
        ///bad log: declare @q nvarchar (200) select @q = 0x770061006900740066006F0072002000640065006C00610079002000270030003A0030003A0031003000270000 exec(@q)
        ///[Stop]
        ///normal log
        ///[Stop]
        ///normal log
        ///[Stop]
        ///bad log: xp_cmdshell
        ///[Stop]
        ///&lt;form method=“POST” action=“&amp;lt;? echo $PHP_SELF; ?&gt;“&amp;gt; 
        ///&lt;input type=“text” name=“search”&gt;&lt;br&gt; 
        ///&lt;input type=“submit” value=“Search”&gt; 
        ///&lt;/form&gt; 
        ///&lt;?php
        ///………
        ///SELECT * FROM users WHERE username LIKE ‘%$search%’ OR [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string logtest {
            get {
                return ResourceManager.GetString("logtest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;;alert(String.fromCharCode(88,83,83))//\&apos;;alert(String.fromCharCode(88,83,83))//&quot;;alert(String.fromCharCode(88,83,83))//\&quot;;alert(String.fromCharCode&lt;script&gt;alert(&apos;xss&apos;)&lt;/script&gt;
        /////--&gt;&lt;/SCRIPT&gt;&quot;&gt;&apos;&gt;&lt;SCRIPT&gt;alert(String.fromCharCode(88,83,83))&lt;/SCRIPT&gt;
        ///&apos;&apos;;!--&quot;&lt;XSS&gt;=&amp;{()}
        ///&lt;SCRIPT SRC=http://ha.ckers.org/xss.js&gt;&lt;/SCRIPT&gt;
        ///&lt;IMG SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;
        ///&lt;IMG SRC=javascript:alert(&apos;XSS&apos;)&gt;
        ///&lt;IMG SRC=javascrscriptipt:alert(&apos;XSS&apos;)&gt;
        ///&lt;IMG SRC=JaVaScRiPt:alert(&apos;XSS&apos;)&gt;
        ///&lt;IMG &quot;&quot;&quot;&gt;&lt;SCRIPT&gt;alert(&quot;XSS&quot;)&lt;/SCRIPT&gt;&quot;&gt;
        ///&lt;IMG SR [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string sql_xss关键词 {
            get {
                return ResourceManager.GetString("sql_xss关键词", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RECONFIGURE
        ///xp_cmdshell
        ///sp_configure
        ///xp_regaddmultistring
        ///xp_regdeletekey
        ///xp_regdeletevalue
        ///xp_regenumkeys
        ///xp_regenumvalues
        ///xp_regread
        ///xp_regrmovemultistring
        ///xp_regwrite
        ///xp_servicecontrol
        ///xp_availablemedia
        ///xp_dirtree
        ///xp_enumdsn
        ///xp_logincofig
        ///xp_makecab
        ///xp_terminate_process 的本地化字符串。
        /// </summary>
        internal static string SQL_攻击存储过程 {
            get {
                return ResourceManager.GetString("SQL_攻击存储过程", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 a&apos; or 1=1--
        ///&quot;a&quot;&quot; or 1=1--&quot;
        /// or a = a
        ///a&apos; or &apos;a&apos; = &apos;a
        ///1 or 1=1
        ///a&apos; waitfor delay &apos;0:0:10&apos;--
        ///1 waitfor delay &apos;0:0:10&apos;--
        ///declare @q nvarchar (200) select @q = 0x770061006900740066006F0072002000640065006C00610079002000270030003A0030003A0031003000270000 exec(@q)
        ///declare @s varchar(200) select @s = 0x77616974666F722064656C61792027303A303A31302700 exec(@s) 
        ///declare @q nvarchar (200) 0x730065006c00650063007400200040004000760065007200730069006f006e00 exec(@q)
        ///declare @s varchar (200) select @s = 0x73656c65637420404076 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SQL_普通注入 {
            get {
                return ResourceManager.GetString("SQL_普通注入", resourceCulture);
            }
        }
    }
}
